name: TFMenv
channels:
  - conda-forge
dependencies:
  - python=3.10
  - esmpy=8.4.2
  - xesmf>=0.7
  - xarray
  - zarr
  - geopandas
  - copernicusmarine
  - numpy
  - pandas
  - matplotlib
  - folium
  - scipy
  - cartopy
  - ipykernel=6.30.1
  - dask
  - bottleneck
  


# conda env create -f 00environment.yml